<?php
/**
 * @file
 * Responsive layouts built on the Bootstrap 3 grid system.
 */

/**
 * Implements hook_theme().
 */
function radix_layouts_theme() {
  // TODO: support auto-registration of theme functions in layout_plugin!
  return array(
    'radix_bryant_flipped' => array(
      'render element' => 'content',
      'path' => drupal_get_path('module', 'radix_layouts') . '/plugins/layouts/radix_bryant_flipped',
      'template' => 'radix-bryant-flipped',
    ),
  );
}
