<?php
// Plugin definition
$plugin = array(
  'title' => t('Radix Sanderson Flipped'),
  'icon' => 'radix-sanderson-flipped.png',
  'category' => t('Radix'),
  'theme' => 'radix_sanderson_flipped',
  'regions' => array(
    'column1' => t('row-fluid 1: First Column'),
    'column2' => t('row-fluid 1: Second Column'),
    'column3' => t('row-fluid 1: Third Column'),
    'secondarycolumn1' => t('row-fluid 2: First Column'),
    'secondarycolumn2' => t('row-fluid 2: Second Column'),
  ),
);
