<?php
// Plugin definition
$plugin = array(
  'title' => t('Radix Sanderson'),
  'icon' => 'radix-sanderson.png',
  'category' => t('Radix'),
  'theme' => 'radix_sanderson',
  'regions' => array(
    'column1' => t('row-fluid 1: First Column'),
    'column2' => t('row-fluid 1: Second Column'),
    'secondarycolumn1' => t('row-fluid 2: First Column'),
    'secondarycolumn2' => t('row-fluid 2: Second Column'),
    'secondarycolumn3' => t('row-fluid 2: Third Column'),
  ),
);
